macro(openomf_strings)
    # strings new in OpenOMF
    openomf_string(LANG2_STR_LANGUAGE "Language name")
endmacro()

macro(base_strings)
    # strings from OMF 2097
    from_base(LANG2_STR_PILOT "Pilots" 20..=30)
    from_base(LANG2_STR_ROBOT "Robots" 31..=41)
    from_base(LANG2_STR_ROBOT_DESCRIPTION "Robot Description" 492..=502)
    from_base(LANG2_STR_ARENA "Arena Name" 56..=60)
    from_base(LANG2_STR_ARENADESCRIPTION "Arena Description" 66..=70)
    from_base(LANG2_STR_PRONOUN "Newsroom Pronouns" 81..=86)
    from_base(LANG2_STR_NEWSROOM_UNRANKEDCHALLENGER_DIALOG "Newsroom Unrnkd Chlngr Dialog" 79)
    from_base(LANG2_STR_NEWSROOM_UNRANKEDCHALLENGER "Newsroom Unranked Challenger" 77..=78)
    from_base(LANG2_STR_NEWSROOM_NEWCHAMPION "Newsroom New Champion" 79)
    from_base(LANG2_STR_NEWSROOM_REPORT "Newsroom Reports" 87..=134)
    from_base(LANG2_STR_CPU_DIFFICULTY "CPU Difficulty" 343..=349)
    from_base(LANG2_STR_TOOPATHETIC_DIALOG "Too Pathetic Dialog" 748)
    from_base(LANG2_STR_TOOPATHETIC_INSULT "Too Pathetic Insult" 747)
    from_base(LANG2_STR_VS_INSULT_1 "VS Insult" 749..=869)
    from_base(LANG2_STR_VS_INSULT_2 "VS Insult Reply" 870..=990)
    from_base(LANG2_STR_PLUG "Plug says" 587..=602)
    from_base(LANG2_STR_PILOTDESCRIPTION "Pilot Biography" 135..=145)
    from_base(LANG2_STR_PILOTSTAT_POWER "Pilot Power Stat" 216)
    from_base(LANG2_STR_PILOTSTAT_SPEED "Pilot Speed Stat" 217)
    from_base(LANG2_STR_PILOTSTAT_ENDURANCE "Pilot Endurance Stat" 218)
    from_base(LANG2_STR_CHOOSEYOUR_PILOT "Choose Pilot" 187)
    from_base(LANG2_STR_CHOOSEYOUR_ROBOT "Choose Robot" 186)
    from_base(LANG2_STR_END "SCENE_END text" 992)
    from_base(LANG2_STR_END1 "SCENE_END1 per-pilot" 993..=1002)
    from_base(LANG2_STR_END2 "SCENE_END2 per-pilot" 1003..=1012)
    from_base(LANG2_STR_SELECT_TOURNAMENT "Select a Tournament" 486)
    from_base(LANG2_STR_SELECT_PHOTO_FOR_CHARACTER "Select Photo for Pilot" 224)
    from_base(LANG2_STR_SELECT_CHARACTER_TO_LOAD "Select Pilot (CHR)" 225)
    from_base(LANG2_STR_SELECT_CHARACTER_TO_DELETE "Select Pilot (CHR)" 226)
    from_base(LANG2_STR_SELECT_OPPONENT "Select Opponent" 227)
    from_base(LANG2_STR_TRAINING_TITLE "Training Title" 512..=514)
    from_base(LANG2_STR_TRAINING_CONFIRMATION "Training Confirmation" 515..=517)
    from_base(LANG2_STR_TRAINING_HELP "Training Help" 533..=535)
    from_base(LANG2_STR_TRAINING_DONE "Leave Training" 536)
    from_base(LANG2_STR_TRADE_GAINCASH "Trade" 518)
    from_base(LANG2_STR_TRADE_SPENDCASH "Trade" 519)
    from_base(LANG2_STR_TRADE_EQUITABLE "Trade" 520)
    from_base(LANG2_STR_BUTTON_SELECT "\"Select\" button" 223)
    from_base(LANG2_STR_TOURNAMENT_FIGHT "Tournament: Fight %s" 223)
    from_base(LANG2_STR_ENTER_TRAINING_HELP "Enter Training Help" 538)
    from_base(LANG2_STR_BUY_UPGRADES_HELP "Buy Upgrade Kits Help" 539)
    from_base(LANG2_STR_SELL_UPGRADES_HELP "Sell Upgrade Kits Help" 540)
    from_base(LANG2_STR_CHR_LOAD_HELP "Pilot Load Help" 541)
    from_base(LANG2_STR_CHR_CREATE_HELP "Pilot Create Help" 542)
    from_base(LANG2_STR_CHR_DELETE_HELP "Pilot Delete Help" 543)
    from_base(LANG2_STR_TOURNAMENT_SIM_HELP "Enter Simulator Help" 544)
    from_base(LANG2_STR_TOURNAMENT_QUIT_HELP "Close Tournament-Mode Help" 545)
    from_base(LANG2_STR_TOURNAMENT_REGISTER_HELP "Tournament Register Help" 546)
    from_base(LANG2_STR_TOURNAMENT_DIFFICULTY "Tournament Difficulty" 444..=447)
    from_base(LANG2_STR_NO "No" 228)
    from_base(LANG2_STR_YES "Yes" 229)
    from_base(LANG2_STR_PROMPT_CHR_NAME "Character Name Prompt" 192)
    from_base(LANG2_STR_CUSTOMIZE_COLOR_1 "Robot Primary color" 547)
    from_base(LANG2_STR_CUSTOMIZE_COLOR_2 "Robot Secondary color" 549)
    from_base(LANG2_STR_CUSTOMIZE_COLOR_3 "Robot Third color" 551)
    from_base(LANG2_STR_UPGRADE_POWER_SELL "Sell Power Upgrade" 553)
    from_base(LANG2_STR_UPGRADE_POWER_BUY "Buy Power Upgrade" 554)
    from_base(LANG2_STR_UPGRADE_SPEED_SELL "Sell Speed Upgrade" 557)
    from_base(LANG2_STR_UPGRADE_SPEED_BUY "Buy Speed Upgrade" 558)
    from_base(LANG2_STR_UPGRADE_ARMOR_SELL "Sell Armor Upgrade" 561)
    from_base(LANG2_STR_UPGRADE_ARMOR_BUY "Buy Armor Upgrade" 562)
    from_base(LANG2_STR_UPGRADE_STUNRESISTANCE_SELL "Sell Stun Res. Upgrade" 563)
    from_base(LANG2_STR_UPGRADE_STUNRESISTANCE_BUY "Buy Stun Res. Upgrade" 564)
    from_base(LANG2_STR_TRADE_HELP "Trade Robot tooltip" 565)
    from_base(LANG2_STR_TRADE_NONEAVAILABLE "No Robots Available" 488)
    from_base(LANG2_STR_TRADE_AVAILABLE "Robots Available:" 461)
    from_base(LANG2_STR_UPGRADE_QUIT_SELL "leave upgrade sell" 567)
    from_base(LANG2_STR_UPGRADE_QUIT_BUY "leave upgrade buy" 568)
endmacro()
